### ISSUE TITLE
Parameter count of the final ensemble

### ISSUE THREAD

**Issue by AdrianKs** [graphcore/distributed-kge-poplar#1]
Hi, thanks for the great work.
On the official leaderboard of wikikg90m-v2 it says your model has a parameter count of 23.4B parameters, which is only slightly larger than the transe-shallow on the board.
However, in your paper you say, the final submission consists of 85 models, each having a minimum embedding size of 256.
This seems to be a considerably larger number. 

Could you please share the parameter count of the final submitted ensemble?

Thanks in advance!

**Comment by AlCatt91** [comment]
Hello Adrian, thanks for your question. The parameter count appearing in the leaderboard for our submission corresponds to the best-performing individual model in our final ensemble (a RotatE run with embedding size 256, achieving a validation MRR of 0.2433). The individual parameter count for the 85 models in our ensemble ranges from 23.3B to 36.5B.

Notice that each model is trained separately, and also at inference time we never need to load the weights of more than one model at the same time (for each query, we just take the individual top-100 predictions from all models and combine them with the strategy explained in the paper). Still, if one wants to sum the number of trainable parameters of all 85 models, the total we get is around 2.6T parameters.

**Comment by AdrianKs** [comment]
Thank you for the quick and detailed reply. This definitely clarifies it.
